version: '3.1'

services:
  app:
    container_name: contact-app
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: contacts
    volumes:
      - mysql-data:/var/lib/mysql
    expose:
      - 3306

volumes:
  mysql-data:
